//! Default-value extraction for OpenAPI schema generation.
//!
//! Handles the three sources of struct field defaults:
//! 1. Pre-extracted `SCHEMA_STORAGE` defaults (populated by `#[derive(Schema)]`)
//! 2. `#[schema(default = "...")]` attributes (generated by `schema_type!`)
//! 3. `#[serde(default)]` / `#[serde(default = "fn_name")]` attributes
//!    (the function variant needs a parsed file AST)

use std::collections::{BTreeMap, BTreeSet, HashMap};

use crate::{
    parser::{
        extract_default, extract_field_rename, extract_rename_all, rename_field,
        strip_raw_prefix_owned,
    },
    schema_macro::type_utils::get_type_default as utils_get_type_default,
};

/// Set the default value on an inline property schema, if not already set.
///
/// Looks up `field_name` in the properties map. If found as an inline schema
/// and the schema has no existing default, sets `value` as the default.
pub(super) fn set_property_default(
    properties: &mut BTreeMap<String, vespera_core::schema::SchemaRef>,
    field_name: &str,
    value: serde_json::Value,
) {
    use vespera_core::schema::{SchemaRef, SchemaType};

    if let Some(SchemaRef::Inline(prop_schema)) = properties.get_mut(field_name)
        && prop_schema.default.is_none()
    {
        // A default on a string-typed property must itself be a string — e.g. a
        // `Decimal` field (string wire type) carrying a numeric DB default value.
        let value = if prop_schema.schema_type == Some(SchemaType::String) {
            match value {
                serde_json::Value::Number(n) => serde_json::Value::String(n.to_string()),
                serde_json::Value::Bool(b) => serde_json::Value::String(b.to_string()),
                other => other,
            }
        } else {
            value
        };
        prop_schema.default = Some(value);
    }
}

/// Process default functions for struct fields
/// This function extracts default values from:
/// 1. `#[schema(default = "value")]` attributes (generated by `schema_type!` from `sea_orm(default_value)`)
/// 2. `#[serde(default = "function_name")]` by finding the function in the file AST
/// 3. `#[serde(default)]` by using type-specific defaults
pub(super) fn process_default_functions(
    struct_item: &syn::ItemStruct,
    file_ast: Option<&syn::File>,
    schema: &mut vespera_core::schema::Schema,
    stored_defaults: &BTreeMap<String, serde_json::Value>,
) {
    use syn::Fields;

    // Cheap O(field_attrs) precheck: when `stored_defaults` is empty AND no
    // field carries a `serde` or `schema` attribute, NONE of the three
    // priority paths below can fire and the `required` demotion stays empty
    // — so the rest of this function is provably a no-op. The early-return
    // is observably equivalent to the full walk: the emitted `Schema` stays
    // byte-identical (the `insta` snapshots in `crates/vespera_macro/src/
    // snapshots/` are the runtime-neutrality lock).
    //
    // Bench fixture (`benches/macro-compile-bench`) has 14 component schemas
    // and NONE carry `#[serde(default)]` / `#[schema(default)]`, so the
    // pre-extracted `field_defaults` is empty for all of them — every full
    // `macro_expand_crate` previously paid ~14 struct-level walks + ~70
    // per-field iterations of `parse_nested_meta` for pure no-op work.
    if stored_defaults.is_empty() && !any_field_carries_default_relevant_attr(struct_item) {
        return;
    }

    // Extract rename_all from struct level
    let struct_rename_all = extract_rename_all(&struct_item.attrs);

    // Locate the object schema that actually holds the fields. Flatten structs
    // are `allOf`-shaped: their own (non-flattened) fields live in the first
    // inline `allOf` member, not a top-level `properties` map — defaults (and
    // the `required` demotion below) must apply there too.
    let Some(target) = field_bearing_schema_mut(schema) else {
        return;
    };

    // Every `#[serde(default)]` field is wire-optional: serde accepts payloads
    // with that key omitted. Requiredness therefore depends on wire presence,
    // not on whether we could statically extract the default value.
    let mut serde_default_fields: BTreeSet<String> = BTreeSet::new();
    let function_index = file_ast.map(function_index_by_name);

    // Process each field in the struct
    if let Some(properties) = target.properties.as_mut()
        && let Fields::Named(fields_named) = &struct_item.fields
    {
        for field in &fields_named.named {
            let rust_field_name = field.ident.as_ref().map_or_else(
                || "unknown".to_string(),
                |i| strip_raw_prefix_owned(i.to_string()),
            );
            let field_name = extract_field_rename(&field.attrs)
                .unwrap_or_else(|| rename_field(&rust_field_name, struct_rename_all.as_deref()));

            // Priority 0: Pre-extracted defaults from SCHEMA_STORAGE (populated by #[derive(Schema)])
            if let Some(value) = stored_defaults.get(&rust_field_name) {
                set_property_default(properties, &field_name, value.clone());
                continue;
            }

            // Priority 1: #[schema(default = "value")] from schema_type! macro.
            // The attribute value is a string literal; for a string-typed field
            // use it VERBATIM so lexical form is preserved (e.g. a leading-zero
            // id `"00123"` must NOT normalise to `"123"`), otherwise infer the
            // JSON type from the string.
            if let Some(default_str) = extract_schema_default_attr(&field.attrs) {
                let is_string_field = matches!(
                    properties.get(&field_name),
                    Some(vespera_core::schema::SchemaRef::Inline(s))
                        if s.schema_type == Some(vespera_core::schema::SchemaType::String)
                );
                let value = if is_string_field {
                    serde_json::Value::String(default_str)
                } else {
                    parse_default_string_to_json_value(&default_str)
                };
                set_property_default(properties, &field_name, value);
                continue;
            }

            // Priority 2: #[serde(default)] / #[serde(default = "fn")]
            let default_info = match extract_default(&field.attrs) {
                Some(Some(func_name)) => {
                    serde_default_fields.insert(field_name.clone());
                    func_name
                }
                Some(None) => {
                    serde_default_fields.insert(field_name.clone());
                    // Simple default (no function): use the type-specific default
                    // when known. Unresolvable defaults are rejected earlier by
                    // `#[derive(Schema)]`, so this fallback only preserves unit
                    // test behaviour when called directly.
                    if let Some(default_value) = utils_get_type_default(&field.ty) {
                        set_property_default(properties, &field_name, default_value);
                    }
                    continue;
                }
                None => continue, // No default attribute
            };

            // Priority 2 (function form) is the only step that needs the AST.
            // Unresolvable values are rejected earlier by `#[derive(Schema)]`;
            // this path simply omits the `default` when invoked directly in
            // tests without that derive-time validation.
            let resolved = function_index
                .as_ref()
                .and_then(|index| find_function_in_index(index, &default_info))
                .and_then(extract_default_value_from_function);
            if let Some(default_value) = resolved {
                set_property_default(properties, &field_name, default_value);
            }
        }
    }

    // Demote every serde-default field from `required`: it is optional on the
    // wire regardless of how the default value was obtained.
    if !serde_default_fields.is_empty() {
        if let Some(required) = target.required.as_mut() {
            required.retain(|name| !serde_default_fields.contains(name));
        }
        if target.required.as_ref().is_some_and(Vec::is_empty) {
            target.required = None;
        }
    }
}

/// Returns `true` if any named field on `struct_item` carries a `#[serde(...)]`
/// or `#[schema(...)]` attribute — the only attributes that can possibly
/// trigger any of `process_default_functions`'s three priority paths.
///
/// Only inspects the attribute path (an `Ident` comparison) — never calls
/// `parse_nested_meta`, so this stays O(sum of field attr counts) byte
/// comparisons. Tuple/unit structs return `false` immediately (matching the
/// `Fields::Named` branch in the caller).
fn any_field_carries_default_relevant_attr(struct_item: &syn::ItemStruct) -> bool {
    let syn::Fields::Named(fields) = &struct_item.fields else {
        return false;
    };
    fields.named.iter().any(|field| {
        field
            .attrs
            .iter()
            .any(|attr| attr.path().is_ident("serde") || attr.path().is_ident("schema"))
    })
}

/// Return the object schema that actually carries the struct's fields: the
/// schema itself, or — for flatten/`allOf`-shaped structs — the first inline
/// `allOf` member (where the non-flattened fields live).
fn field_bearing_schema_mut(
    schema: &mut vespera_core::schema::Schema,
) -> Option<&mut vespera_core::schema::Schema> {
    if schema.properties.is_some() {
        return Some(schema);
    }
    schema
        .all_of
        .as_mut()?
        .iter_mut()
        .find_map(|member| match member {
            vespera_core::schema::SchemaRef::Inline(inline) => Some(inline.as_mut()),
            vespera_core::schema::SchemaRef::Ref(_) => None,
        })
}

/// Extract `default` value from `#[schema(default = "...")]` field attribute.
///
/// This attribute is generated by `schema_type!` when converting `sea_orm(default_value)`.
/// It carries the raw default value string for OpenAPI schema generation.
pub(super) fn extract_schema_default_attr(attrs: &[syn::Attribute]) -> Option<String> {
    attrs
        .iter()
        .filter(|attr| attr.path().is_ident("schema"))
        .find_map(|attr| {
            let mut default_value = None;
            let _ = attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("default") {
                    let value = meta.value()?;
                    let lit: syn::LitStr = value.parse()?;
                    default_value = Some(lit.value());
                }
                Ok(())
            });
            default_value
        })
}

/// Parse a default value string into the appropriate `serde_json::Value`.
///
/// Tries to infer the JSON type: integer → number → bool → string (fallback).
pub(super) fn parse_default_string_to_json_value(value: &str) -> serde_json::Value {
    // Try integer first
    if let Ok(n) = value.parse::<i64>() {
        return serde_json::Value::Number(n.into());
    }
    // Try float
    if let Ok(f) = value.parse::<f64>()
        && let Some(n) = serde_json::Number::from_f64(f)
    {
        return serde_json::Value::Number(n);
    }
    // Try bool
    if let Ok(b) = value.parse::<bool>() {
        return serde_json::Value::Bool(b);
    }
    // Fallback to string
    serde_json::Value::String(value.to_string())
}

/// Find a function by name in the file AST
#[cfg(test)]
pub fn find_function_in_file<'a>(
    file_ast: &'a syn::File,
    function_name: &str,
) -> Option<&'a syn::ItemFn> {
    let index = function_index_by_name(file_ast);
    find_function_in_index(&index, function_name)
}

fn function_index_by_name(file_ast: &syn::File) -> HashMap<String, &syn::ItemFn> {
    let mut functions = HashMap::new();
    for item in &file_ast.items {
        if let syn::Item::Fn(fn_item) = item {
            functions
                .entry(fn_item.sig.ident.to_string())
                .or_insert(fn_item);
        }
    }
    functions
}

fn find_function_in_index<'a>(
    function_index: &HashMap<String, &'a syn::ItemFn>,
    function_name: &str,
) -> Option<&'a syn::ItemFn> {
    let local_name = function_name.rsplit("::").next().unwrap_or(function_name);
    function_index.get(local_name).copied()
}

/// Extract default value from function body
/// This tries to extract literal values from common patterns like:
/// - "`value".to_string()` -> "value"
/// - 42 -> 42
/// - true -> true
/// - vec![] -> []
pub fn extract_default_value_from_function(func: &syn::ItemFn) -> Option<serde_json::Value> {
    // Try to find return statement or expression
    for stmt in &func.block.stmts {
        if let syn::Stmt::Expr(expr, _) = stmt {
            // Direct expression (like "value".to_string())
            if let Some(value) = extract_value_from_expr(expr) {
                return Some(value);
            }
            // Or return statement
            if let syn::Expr::Return(ret) = expr
                && let Some(expr) = &ret.expr
                && let Some(value) = extract_value_from_expr(expr)
            {
                return Some(value);
            }
        }
    }

    None
}

/// Extract value from expression
pub(super) fn extract_value_from_expr(expr: &syn::Expr) -> Option<serde_json::Value> {
    use syn::{Expr, ExprLit, ExprMacro, Lit};

    match expr {
        // Literal values
        Expr::Lit(ExprLit { lit, .. }) => match lit {
            Lit::Str(s) => Some(serde_json::Value::String(s.value())),
            Lit::Int(i) => i
                .base10_parse::<i64>()
                .ok()
                .map(|v| serde_json::Value::Number(v.into())),
            Lit::Float(f) => f
                .base10_parse::<f64>()
                .ok()
                .and_then(serde_json::Number::from_f64)
                .map(serde_json::Value::Number),
            Lit::Bool(b) => Some(serde_json::Value::Bool(b.value)),
            _ => None,
        },
        // Method calls like "value".to_string()
        Expr::MethodCall(method_call) => {
            if method_call.method == "to_string" {
                // Get the receiver (the string literal)
                // Try direct match first
                if let Expr::Lit(ExprLit {
                    lit: Lit::Str(s), ..
                }) = method_call.receiver.as_ref()
                {
                    return Some(serde_json::Value::String(s.value()));
                }
                // Try to extract from nested expressions (e.g., if the receiver is wrapped)
                if let Some(value) = extract_value_from_expr(method_call.receiver.as_ref()) {
                    return Some(value);
                }
            }
            None
        }
        // Associated function calls like String::from("value")
        Expr::Call(call) => {
            let Expr::Path(path) = call.func.as_ref() else {
                return None;
            };
            let mut segments = path.path.segments.iter().rev();
            let last = segments.next()?;
            let prev = segments.next()?;
            if last.ident == "from"
                && prev.ident == "String"
                && call.args.len() == 1
                && let Some(first_arg) = call.args.first()
            {
                return extract_value_from_expr(first_arg).and_then(|value| match value {
                    serde_json::Value::String(_) => Some(value),
                    _ => None,
                });
            }
            None
        }
        // Macro calls like vec![...]
        Expr::Macro(ExprMacro { mac, .. }) => {
            if mac.path.is_ident("vec") {
                // `vec![]` → empty array.  `vec![a, b, ...]` → the array of its
                // element values, but ONLY when every element resolves to a
                // literal; otherwise the default is unrepresentable and we
                // return `None` (the field is then demoted from `required`)
                // rather than emitting a WRONG empty `[]` for a non-empty
                // `vec!` (the prior behaviour silently dropped the elements).
                if mac.tokens.is_empty() {
                    return Some(serde_json::Value::Array(Vec::new()));
                }
                return mac
                    .parse_body_with(
                        syn::punctuated::Punctuated::<Expr, syn::Token![,]>::parse_terminated,
                    )
                    .ok()
                    .and_then(|elems| {
                        elems
                            .iter()
                            .map(extract_value_from_expr)
                            .collect::<Option<Vec<_>>>()
                    })
                    .map(serde_json::Value::Array);
            }
            None
        }
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use rstest::rstest;
    use serde_json::{Value, json};
    use vespera_core::schema::{Reference, Schema, SchemaRef};

    use super::*;

    fn parse_expr(src: &str) -> syn::Expr {
        syn::parse_str(src).expect("expr parses")
    }

    fn parse_fn(src: &str) -> syn::ItemFn {
        syn::parse_str(src).expect("fn parses")
    }

    fn parse_type(src: &str) -> syn::Type {
        syn::parse_str(src).expect("type parses")
    }

    // ---------- extract_value_from_expr ----------

    #[rstest]
    #[case::int("42", Some(Value::Number(42.into())))]
    #[case::string(r#""hello""#, Some(Value::String("hello".to_string())))]
    #[case::bool_true("true", Some(Value::Bool(true)))]
    #[case::bool_false("false", Some(Value::Bool(false)))]
    #[case::to_string(r#""hello".to_string()"#, Some(Value::String("hello".to_string())))]
    #[case::string_from(r#"String::from("hello")"#, Some(Value::String("hello".to_string())))]
    #[case::vec_macro("vec![]", Some(Value::Array(vec![])))]
    #[case::vec_macro_nonempty("vec![1, 2, 3]", Some(json!([1, 2, 3])))]
    #[case::vec_macro_strings(r#"vec!["a", "b"]"#, Some(json!(["a", "b"])))]
    #[case::vec_macro_unresolvable("vec![some_var]", None)]
    #[case::int_to_string("42.to_string()", Some(Value::Number(42.into())))]
    #[case::binary_unsupported("1 + 2", None)]
    #[case::method_call_non_to_string(r#""hello".len()"#, None)]
    #[case::byte_lit_unsupported("b'a'", None)]
    #[case::non_vec_macro(r#"println!("test")"#, None)]
    #[case::nested_paren_receiver(r#"("hello").to_string()"#, None)]
    #[case::non_literal_receiver("some_var.to_string()", None)]
    #[case::int_overflow("999999999999999999999999999999", None)]
    fn extract_value_from_expr_cases(#[case] src: &str, #[case] expected: Option<Value>) {
        assert_eq!(extract_value_from_expr(&parse_expr(src)), expected);
    }

    #[test]
    fn extract_value_from_expr_float_in_range() {
        // Float equality probe is separate — 12.34 round-trips but the assertion
        // needs a tolerance check rather than direct equality.
        let value = extract_value_from_expr(&parse_expr("12.34"));
        match value {
            Some(Value::Number(n)) => assert!((n.as_f64().unwrap() - 12.34).abs() < 0.001),
            other => panic!("expected number, got {other:?}"),
        }
    }

    #[test]
    fn extract_value_from_expr_float_parse_failure_does_not_panic() {
        // 1e999999 may parse to infinity or fail — either way the call must not panic.
        let _ = extract_value_from_expr(&parse_expr("1e999999"));
    }

    // ---------- get_type_default (re-exported helper) ----------

    #[rstest]
    #[case::string("String", Some(Value::String(String::new())))]
    #[case::i8("i8", Some(Value::Number(0.into())))]
    #[case::i16("i16", Some(Value::Number(0.into())))]
    #[case::i32("i32", Some(Value::Number(0.into())))]
    #[case::i64("i64", Some(Value::Number(0.into())))]
    #[case::u8("u8", Some(Value::Number(0.into())))]
    #[case::u16("u16", Some(Value::Number(0.into())))]
    #[case::u32("u32", Some(Value::Number(0.into())))]
    #[case::u64("u64", Some(Value::Number(0.into())))]
    #[case::bool("bool", Some(Value::Bool(false)))]
    #[case::unknown_custom("CustomType", None)]
    #[case::non_path_ref("&str", None)]
    #[case::tuple("(i32, String)", None)]
    #[case::array("[i32; 3]", None)]
    fn get_type_default_cases(#[case] src: &str, #[case] expected: Option<Value>) {
        assert_eq!(utils_get_type_default(&parse_type(src)), expected);
    }

    #[rstest]
    #[case::f32("f32")]
    #[case::f64("f64")]
    fn get_type_default_floats_present(#[case] src: &str) {
        assert!(utils_get_type_default(&parse_type(src)).is_some());
    }

    #[test]
    fn get_type_default_global_path_still_resolved() {
        // `::String` has a leading colon-colon but the last segment is still `String`.
        assert!(utils_get_type_default(&parse_type("::String")).is_some());
    }

    // ---------- find_function_in_file ----------

    #[rstest]
    #[case("foo", true)]
    #[case("defaults::foo", true)]
    #[case("bar", true)]
    #[case("baz", true)]
    #[case("nonexistent", false)]
    fn find_function_in_file_cases(#[case] needle: &str, #[case] expected: bool) {
        let file: syn::File = syn::parse_str(
            r"
            fn foo() {}
            fn bar() -> i32 { 42 }
            fn baz(x: i32) -> i32 { x }
            ",
        )
        .unwrap();
        assert_eq!(find_function_in_file(&file, needle).is_some(), expected);
    }

    // ---------- extract_default_value_from_function ----------

    #[test]
    fn extract_default_value_from_function_direct_expr() {
        let func = parse_fn("fn default_value() -> i32 { 42 }");
        assert_eq!(
            extract_default_value_from_function(&func),
            Some(Value::Number(42.into()))
        );
    }

    #[test]
    fn extract_default_value_from_function_explicit_return() {
        let func = parse_fn(r#"fn default_value() -> String { return "hello".to_string() }"#);
        assert_eq!(
            extract_default_value_from_function(&func),
            Some(Value::String("hello".to_string()))
        );
    }

    #[test]
    fn process_default_functions_applies_string_default_fn_value() {
        let file_ast: syn::File = syn::parse_str(
            r#"
            fn default_sort() -> String { "asc".to_string() }
            fn default_direction() -> String { String::from("desc") }
            "#,
        )
        .unwrap();
        let struct_item: syn::ItemStruct = syn::parse_str(
            r#"
            pub struct Test {
                #[serde(default = "default_sort")]
                pub sort: String,
                #[serde(default = "default_direction")]
                pub direction: String,
            }
            "#,
        )
        .unwrap();
        let mut schema = Schema::object();
        let props = schema.properties.get_or_insert_with(BTreeMap::new);
        props.insert(
            "sort".to_string(),
            SchemaRef::Inline(Box::new(Schema::string())),
        );
        props.insert(
            "direction".to_string(),
            SchemaRef::Inline(Box::new(Schema::string())),
        );

        process_default_functions(&struct_item, Some(&file_ast), &mut schema, &BTreeMap::new());

        let properties = schema.properties.as_ref().unwrap();
        assert_inline_default(properties, "sort", &json!("asc"));
        assert_inline_default(properties, "direction", &json!("desc"));
    }

    #[test]
    fn process_default_functions_preserves_lexical_string_default() {
        // A `#[schema(default = "...")]` on a string field must keep the literal
        // verbatim — a numeric-looking default like a zero-padded id must NOT be
        // parsed to a number and back (which dropped leading zeroes:
        // "00123" -> "123").
        let struct_item: syn::ItemStruct = syn::parse_str(
            r#"
            pub struct Test {
                #[schema(default = "00123")]
                pub zip: String,
            }
            "#,
        )
        .unwrap();
        let mut schema = Schema::object();
        let props = schema.properties.get_or_insert_with(BTreeMap::new);
        props.insert(
            "zip".to_string(),
            SchemaRef::Inline(Box::new(Schema::string())),
        );

        process_default_functions(&struct_item, None, &mut schema, &BTreeMap::new());

        let properties = schema.properties.as_ref().unwrap();
        assert_inline_default(properties, "zip", &json!("00123"));
    }

    #[test]
    fn extract_default_value_from_function_no_value() {
        let func = parse_fn("fn default_value() { let x = 1; }");
        assert!(extract_default_value_from_function(&func).is_none());
    }

    // ---------- extract_schema_default_attr ----------

    #[rstest]
    #[case::with_value(
        syn::parse_quote!(#[schema(default = "42")]),
        Some("42".to_string()),
    )]
    #[case::no_default(syn::parse_quote!(#[schema(rename = "foo")]), None)]
    #[case::non_schema(syn::parse_quote!(#[serde(default)]), None)]
    fn extract_schema_default_attr_cases(
        #[case] attr: syn::Attribute,
        #[case] expected: Option<String>,
    ) {
        assert_eq!(extract_schema_default_attr(&[attr]), expected);
    }

    // ---------- parse_default_string_to_json_value ----------

    #[rstest]
    #[case::integer("42", json!(42))]
    #[case::float("2.72", json!(2.72))]
    #[case::bool("true", json!(true))]
    #[case::string_fallback("hello world", json!("hello world"))]
    fn parse_default_string_to_json_value_cases(#[case] input: &str, #[case] expected: Value) {
        assert_eq!(parse_default_string_to_json_value(input), expected);
    }

    // ---------- set_property_default ----------

    fn inline_prop(default: Option<Value>) -> SchemaRef {
        let mut schema = Schema::object();
        schema.default = default;
        SchemaRef::Inline(Box::new(schema))
    }

    fn assert_inline_default(
        properties: &BTreeMap<String, SchemaRef>,
        key: &str,
        expected: &Value,
    ) {
        let SchemaRef::Inline(prop) = properties.get(key).expect("property present") else {
            panic!("expected inline schema for {key}");
        };
        assert_eq!(prop.default.as_ref(), Some(expected));
    }

    #[test]
    fn set_property_default_sets_value_on_inline_schema_with_no_default() {
        let mut properties = BTreeMap::new();
        properties.insert("name".to_string(), inline_prop(None));

        set_property_default(&mut properties, "name", json!("Alice"));

        assert_inline_default(&properties, "name", &json!("Alice"));
    }

    #[test]
    fn set_property_default_does_not_overwrite_existing() {
        let mut properties = BTreeMap::new();
        properties.insert("name".to_string(), inline_prop(Some(json!("existing"))));

        set_property_default(&mut properties, "name", json!("new"));

        assert_inline_default(&properties, "name", &json!("existing"));
    }

    #[test]
    fn set_property_default_skips_ref_schema() {
        let mut properties = BTreeMap::new();
        properties.insert(
            "user".to_string(),
            SchemaRef::Ref(Reference::schema("User")),
        );

        set_property_default(&mut properties, "user", json!("ignored"));

        assert!(matches!(properties.get("user"), Some(SchemaRef::Ref(_))));
    }

    #[test]
    fn set_property_default_skips_missing_property() {
        let mut properties = BTreeMap::new();

        set_property_default(&mut properties, "nonexistent", json!(42));

        assert!(properties.is_empty());
    }

    // ---------- process_default_functions ----------

    #[test]
    fn process_default_functions_early_returns_when_properties_none() {
        let struct_item: syn::ItemStruct = syn::parse_str("struct Empty;").unwrap();
        let file_ast: syn::File = syn::parse_str("fn foo() {}").unwrap();
        let mut schema = Schema::object();
        schema.properties = None;

        process_default_functions(&struct_item, Some(&file_ast), &mut schema, &BTreeMap::new());

        assert!(schema.properties.is_none());
    }

    #[test]
    fn process_default_functions_applies_schema_default_attr() {
        let file_ast: syn::File = syn::parse_str("").unwrap();
        let struct_item: syn::ItemStruct =
            syn::parse_str(r#"pub struct Test { #[schema(default = "100")] pub count: i32 }"#)
                .unwrap();
        let mut schema = Schema::object();
        let props = schema.properties.get_or_insert_with(BTreeMap::new);
        props.insert(
            "count".to_string(),
            SchemaRef::Inline(Box::new(Schema::integer())),
        );

        process_default_functions(&struct_item, Some(&file_ast), &mut schema, &BTreeMap::new());

        assert_inline_default(schema.properties.as_ref().unwrap(), "count", &json!(100));
    }

    #[test]
    fn process_default_functions_applies_default_into_flatten_allof_member() {
        // Flatten struct: the own field `sort` (defaulted) lives in the inline
        // `allOf[0]` member, `pagination` is flattened to a `$ref`. The default
        // must still land on `sort` even though there is no top-level
        // `properties` map.
        let file_ast: syn::File =
            syn::parse_str(r#"fn default_sort() -> String { "asc".to_string() }"#).unwrap();
        let struct_item: syn::ItemStruct = syn::parse_str(
            r#"
            pub struct UserListRequest {
                #[serde(default = "default_sort")]
                pub sort: String,
                #[serde(flatten)]
                pub pagination: Pagination,
            }
            "#,
        )
        .unwrap();

        let mut inline = Schema::object();
        inline.properties.get_or_insert_with(BTreeMap::new).insert(
            "sort".to_string(),
            SchemaRef::Inline(Box::new(Schema::string())),
        );
        let mut schema = Schema::default();
        schema.all_of = Some(vec![
            SchemaRef::Inline(Box::new(inline)),
            SchemaRef::Ref(Reference::schema("Pagination")),
        ]);

        process_default_functions(&struct_item, Some(&file_ast), &mut schema, &BTreeMap::new());

        let all_of = schema.all_of.as_ref().expect("allOf present");
        let SchemaRef::Inline(inline) = &all_of[0] else {
            panic!("expected inline allOf member");
        };
        assert_inline_default(inline.properties.as_ref().unwrap(), "sort", &json!("asc"));
    }

    #[test]
    fn process_default_functions_demotes_unresolvable_fn_default_from_required() {
        // `#[serde(default = "fn")]` whose body is not a simple literal: no value
        // can be extracted at compile time, so the field must drop out of
        // `required` (a required field with no default is unsatisfiable).
        let file_ast: syn::File =
            syn::parse_str("fn complex() -> Vec<String> { compute_tags() }").unwrap();
        let struct_item: syn::ItemStruct = syn::parse_str(
            r#"
            pub struct Req {
                pub name: String,
                #[serde(default = "complex")]
                pub tags: Vec<String>,
            }
            "#,
        )
        .unwrap();
        let mut schema = Schema::object();
        let props = schema.properties.get_or_insert_with(BTreeMap::new);
        props.insert(
            "name".to_string(),
            SchemaRef::Inline(Box::new(Schema::string())),
        );
        props.insert(
            "tags".to_string(),
            SchemaRef::Inline(Box::new(Schema::object())),
        );
        schema.required = Some(vec!["name".to_string(), "tags".to_string()]);

        process_default_functions(&struct_item, Some(&file_ast), &mut schema, &BTreeMap::new());

        let required = schema.required.as_ref().expect("required present");
        assert!(
            required.contains(&"name".to_string()),
            "name stays required"
        );
        assert!(
            !required.contains(&"tags".to_string()),
            "tags must be demoted: its serde default cannot be expressed"
        );
    }

    #[test]
    fn process_default_functions_demotes_simple_default_without_type_default() {
        // `#[serde(default)]` on `Vec<T>`: `get_type_default` yields no value for
        // Vec, so the field is demoted from `required`.
        let struct_item: syn::ItemStruct = syn::parse_str(
            r"
            pub struct Req {
                pub name: String,
                #[serde(default)]
                pub tags: Vec<String>,
            }
            ",
        )
        .unwrap();
        let mut schema = Schema::object();
        let props = schema.properties.get_or_insert_with(BTreeMap::new);
        props.insert(
            "name".to_string(),
            SchemaRef::Inline(Box::new(Schema::string())),
        );
        props.insert(
            "tags".to_string(),
            SchemaRef::Inline(Box::new(Schema::object())),
        );
        schema.required = Some(vec!["name".to_string(), "tags".to_string()]);

        process_default_functions(&struct_item, None, &mut schema, &BTreeMap::new());

        let required = schema.required.as_ref().expect("required present");
        assert!(required.contains(&"name".to_string()));
        assert!(
            !required.contains(&"tags".to_string()),
            "Vec serde default demoted"
        );
    }

    #[test]
    fn process_default_functions_demotes_required_when_default_resolvable() {
        // A resolvable default still means the field is wire-optional: serde
        // accepts the payload with the key omitted and fills the value locally.
        let file_ast: syn::File =
            syn::parse_str(r#"fn default_sort() -> String { "asc".to_string() }"#).unwrap();
        let struct_item: syn::ItemStruct = syn::parse_str(
            r#"pub struct Req { #[serde(default = "default_sort")] pub sort: String }"#,
        )
        .unwrap();
        let mut schema = Schema::object();
        schema.properties.get_or_insert_with(BTreeMap::new).insert(
            "sort".to_string(),
            SchemaRef::Inline(Box::new(Schema::string())),
        );
        schema.required = Some(vec!["sort".to_string()]);

        process_default_functions(&struct_item, Some(&file_ast), &mut schema, &BTreeMap::new());

        assert!(schema.required.is_none(), "serde-default field is optional");
        assert_inline_default(schema.properties.as_ref().unwrap(), "sort", &json!("asc"));
    }

    // ---------- any_field_carries_default_relevant_attr ----------

    #[rstest]
    // No fields / no attrs: nothing to do, helper returns false.
    #[case::no_fields("pub struct Empty;", false)]
    #[case::tuple_struct("pub struct T(i32, String);", false)]
    #[case::unit_struct("pub struct U;", false)]
    #[case::plain_fields("pub struct P { pub a: i32, pub b: String }", false)]
    // Non-serde/non-schema attrs: helper returns false, early-return fires.
    #[case::doc_only("pub struct D { /// docs\n pub a: i32 }", false)]
    #[case::garde_only(r"pub struct G { #[garde(length(min = 1))] pub a: String }", false)]
    // Serde attrs of ANY kind (rename, default, skip, ...): return true.
    #[case::serde_rename(r#"pub struct S { #[serde(rename = "a")] pub field: String }"#, true)]
    #[case::serde_default_bare("pub struct S { #[serde(default)] pub field: String }", true)]
    #[case::serde_default_fn(r#"pub struct S { #[serde(default = "f")] pub field: String }"#, true)]
    // Schema attrs of ANY kind: return true.
    #[case::schema_default(r#"pub struct S { #[schema(default = "1")] pub field: i32 }"#, true)]
    // Mixed attr lists: any one match is enough.
    #[case::serde_on_second_field(
        r#"pub struct M { pub a: i32, #[serde(rename = "x")] pub b: String }"#,
        true
    )]
    fn any_field_carries_default_relevant_attr_cases(#[case] src: &str, #[case] expected: bool) {
        let struct_item: syn::ItemStruct = syn::parse_str(src).expect("struct parses");
        assert_eq!(
            any_field_carries_default_relevant_attr(&struct_item),
            expected
        );
    }

    // ---------- early-return short-circuit ----------

    #[test]
    fn process_default_functions_early_returns_when_no_defaults_possible() {
        // The bench-fixture pattern: empty `stored_defaults`, no serde/schema
        // attrs anywhere. Every priority path is provably a no-op, so the
        // function must early-return WITHOUT mutating the schema and WITHOUT
        // demoting the field from `required`.
        let struct_item: syn::ItemStruct =
            syn::parse_str("pub struct Plain { pub id: i32, pub name: String }").unwrap();
        let mut schema = Schema::object();
        let props = schema.properties.get_or_insert_with(BTreeMap::new);
        props.insert(
            "id".to_string(),
            SchemaRef::Inline(Box::new(Schema::integer())),
        );
        props.insert(
            "name".to_string(),
            SchemaRef::Inline(Box::new(Schema::string())),
        );
        schema.required = Some(vec!["id".to_string(), "name".to_string()]);

        process_default_functions(&struct_item, None, &mut schema, &BTreeMap::new());

        let properties = schema.properties.as_ref().unwrap();
        let SchemaRef::Inline(id) = properties.get("id").unwrap() else {
            panic!("expected inline");
        };
        let SchemaRef::Inline(name) = properties.get("name").unwrap() else {
            panic!("expected inline");
        };
        assert!(id.default.is_none(), "no default must be set on `id`");
        assert!(name.default.is_none(), "no default must be set on `name`");
        // `required` must be unchanged — no serde-default field exists.
        assert_eq!(
            schema.required.as_deref(),
            Some(["id".to_string(), "name".to_string()].as_slice())
        );
    }

    #[test]
    fn process_default_functions_falls_through_for_serde_rename_only() {
        // `#[serde(rename = ...)]` is not a default attribute, but the helper
        // intentionally treats ANY `serde` attr as relevant — so the full walk
        // must still run (no early-return). The OUTCOME is the same as the
        // early-return path (no defaults set, `required` unchanged) because
        // `rename` is not a default, but we lock that behaviour here so a
        // future change to the helper (e.g. narrowing to `default`-only attrs)
        // does not silently flip semantics.
        let struct_item: syn::ItemStruct = syn::parse_str(
            r#"
            pub struct R {
                #[serde(rename = "n")]
                pub name: String,
            }
            "#,
        )
        .unwrap();
        let mut schema = Schema::object();
        let props = schema.properties.get_or_insert_with(BTreeMap::new);
        props.insert(
            "n".to_string(),
            SchemaRef::Inline(Box::new(Schema::string())),
        );
        schema.required = Some(vec!["n".to_string()]);

        process_default_functions(&struct_item, None, &mut schema, &BTreeMap::new());

        let properties = schema.properties.as_ref().unwrap();
        let SchemaRef::Inline(n) = properties.get("n").unwrap() else {
            panic!("expected inline");
        };
        assert!(n.default.is_none(), "rename-only does not set a default");
        assert_eq!(
            schema.required.as_deref(),
            Some(["n".to_string()].as_slice())
        );
    }

    #[test]
    fn process_default_functions_falls_through_when_stored_defaults_present() {
        // `stored_defaults` populated by `#[derive(Schema)]`: even without any
        // field-level attrs the early-return MUST NOT fire — the Priority-0
        // path must apply the stored default.
        let struct_item: syn::ItemStruct =
            syn::parse_str("pub struct Plain { pub count: i32 }").unwrap();
        let mut schema = Schema::object();
        schema.properties.get_or_insert_with(BTreeMap::new).insert(
            "count".to_string(),
            SchemaRef::Inline(Box::new(Schema::integer())),
        );
        let stored: BTreeMap<String, Value> = BTreeMap::from([("count".to_string(), json!(7))]);

        process_default_functions(&struct_item, None, &mut schema, &stored);

        assert_inline_default(schema.properties.as_ref().unwrap(), "count", &json!(7));
    }

    #[test]
    fn process_default_functions_falls_through_for_schema_default_attr() {
        // `#[schema(default = "...")]` with empty `stored_defaults`: the
        // early-return MUST NOT fire because Priority-1 needs to run.
        let struct_item: syn::ItemStruct = syn::parse_str(
            r#"
            pub struct S {
                #[schema(default = "42")]
                pub count: i32,
            }
            "#,
        )
        .unwrap();
        let mut schema = Schema::object();
        schema.properties.get_or_insert_with(BTreeMap::new).insert(
            "count".to_string(),
            SchemaRef::Inline(Box::new(Schema::integer())),
        );

        process_default_functions(&struct_item, None, &mut schema, &BTreeMap::new());

        assert_inline_default(schema.properties.as_ref().unwrap(), "count", &json!(42));
    }
}
