//! Default-value extraction for OpenAPI schema generation.
//!
//! Handles the three sources of struct field defaults:
//! 1. Pre-extracted `SCHEMA_STORAGE` defaults (populated by `#[derive(Schema)]`)
//! 2. `#[schema(default = "...")]` attributes (generated by `schema_type!`)
//! 3. `#[serde(default)]` / `#[serde(default = "fn_name")]` attributes
//!    (the function variant needs a parsed file AST)

use std::collections::BTreeMap;

use crate::{
    parser::{
        extract_default, extract_field_rename, extract_rename_all, rename_field,
        strip_raw_prefix_owned,
    },
    schema_macro::type_utils::get_type_default as utils_get_type_default,
};

/// Set the default value on an inline property schema, if not already set.
///
/// Looks up `field_name` in the properties map. If found as an inline schema
/// and the schema has no existing default, sets `value` as the default.
pub(super) fn set_property_default(
    properties: &mut BTreeMap<String, vespera_core::schema::SchemaRef>,
    field_name: &str,
    value: serde_json::Value,
) {
    use vespera_core::schema::SchemaRef;

    if let Some(SchemaRef::Inline(prop_schema)) = properties.get_mut(field_name)
        && prop_schema.default.is_none()
    {
        prop_schema.default = Some(value);
    }
}

/// Process default functions for struct fields
/// This function extracts default values from:
/// 1. `#[schema(default = "value")]` attributes (generated by `schema_type!` from `sea_orm(default_value)`)
/// 2. `#[serde(default = "function_name")]` by finding the function in the file AST
/// 3. `#[serde(default)]` by using type-specific defaults
pub(super) fn process_default_functions(
    struct_item: &syn::ItemStruct,
    file_ast: Option<&syn::File>,
    schema: &mut vespera_core::schema::Schema,
    stored_defaults: &BTreeMap<String, serde_json::Value>,
) {
    use syn::Fields;

    // Extract rename_all from struct level
    let struct_rename_all = extract_rename_all(&struct_item.attrs);

    // Get properties from schema
    let Some(properties) = &mut schema.properties else {
        return;
    };

    // Process each field in the struct
    if let Fields::Named(fields_named) = &struct_item.fields {
        for field in &fields_named.named {
            let rust_field_name = field.ident.as_ref().map_or_else(
                || "unknown".to_string(),
                |i| strip_raw_prefix_owned(i.to_string()),
            );
            let field_name = extract_field_rename(&field.attrs)
                .unwrap_or_else(|| rename_field(&rust_field_name, struct_rename_all.as_deref()));

            // Priority 0: Pre-extracted defaults from SCHEMA_STORAGE (populated by #[derive(Schema)])
            if let Some(value) = stored_defaults.get(&rust_field_name) {
                set_property_default(properties, &field_name, value.clone());
                continue;
            }

            // Priority 1: #[schema(default = "value")] from schema_type! macro
            if let Some(default_str) = extract_schema_default_attr(&field.attrs) {
                let value = parse_default_string_to_json_value(&default_str);
                set_property_default(properties, &field_name, value);
                continue;
            }

            // Priority 2: #[serde(default)] / #[serde(default = "fn")]
            let default_info = match extract_default(&field.attrs) {
                Some(Some(func_name)) => func_name, // default = "function_name"
                Some(None) => {
                    // Simple default (no function) - we can set type-specific defaults
                    if let Some(default_value) = utils_get_type_default(&field.ty) {
                        set_property_default(properties, &field_name, default_value);
                    }
                    continue;
                }
                None => continue, // No default attribute
            };

            // Find the function in the file AST and extract default
            // value — Priority 2 is the only step that needs the AST,
            // so it degrades gracefully when none is available.
            if let Some(func_item) =
                file_ast.and_then(|ast| find_function_in_file(ast, &default_info))
                && let Some(default_value) = extract_default_value_from_function(func_item)
            {
                set_property_default(properties, &field_name, default_value);
            }
        }
    }
}

/// Extract `default` value from `#[schema(default = "...")]` field attribute.
///
/// This attribute is generated by `schema_type!` when converting `sea_orm(default_value)`.
/// It carries the raw default value string for OpenAPI schema generation.
pub(super) fn extract_schema_default_attr(attrs: &[syn::Attribute]) -> Option<String> {
    attrs
        .iter()
        .filter(|attr| attr.path().is_ident("schema"))
        .find_map(|attr| {
            let mut default_value = None;
            let _ = attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("default") {
                    let value = meta.value()?;
                    let lit: syn::LitStr = value.parse()?;
                    default_value = Some(lit.value());
                }
                Ok(())
            });
            default_value
        })
}

/// Parse a default value string into the appropriate `serde_json::Value`.
///
/// Tries to infer the JSON type: integer → number → bool → string (fallback).
pub(super) fn parse_default_string_to_json_value(value: &str) -> serde_json::Value {
    // Try integer first
    if let Ok(n) = value.parse::<i64>() {
        return serde_json::Value::Number(n.into());
    }
    // Try float
    if let Ok(f) = value.parse::<f64>()
        && let Some(n) = serde_json::Number::from_f64(f)
    {
        return serde_json::Value::Number(n);
    }
    // Try bool
    if let Ok(b) = value.parse::<bool>() {
        return serde_json::Value::Bool(b);
    }
    // Fallback to string
    serde_json::Value::String(value.to_string())
}

/// Find a function by name in the file AST
pub fn find_function_in_file<'a>(
    file_ast: &'a syn::File,
    function_name: &str,
) -> Option<&'a syn::ItemFn> {
    file_ast.items.iter().find_map(|item| match item {
        syn::Item::Fn(fn_item) if fn_item.sig.ident == function_name => Some(fn_item),
        _ => None,
    })
}

/// Extract default value from function body
/// This tries to extract literal values from common patterns like:
/// - "`value".to_string()` -> "value"
/// - 42 -> 42
/// - true -> true
/// - vec![] -> []
pub fn extract_default_value_from_function(func: &syn::ItemFn) -> Option<serde_json::Value> {
    // Try to find return statement or expression
    for stmt in &func.block.stmts {
        if let syn::Stmt::Expr(expr, _) = stmt {
            // Direct expression (like "value".to_string())
            if let Some(value) = extract_value_from_expr(expr) {
                return Some(value);
            }
            // Or return statement
            if let syn::Expr::Return(ret) = expr
                && let Some(expr) = &ret.expr
                && let Some(value) = extract_value_from_expr(expr)
            {
                return Some(value);
            }
        }
    }

    None
}

/// Extract value from expression
pub(super) fn extract_value_from_expr(expr: &syn::Expr) -> Option<serde_json::Value> {
    use syn::{Expr, ExprLit, ExprMacro, Lit};

    match expr {
        // Literal values
        Expr::Lit(ExprLit { lit, .. }) => match lit {
            Lit::Str(s) => Some(serde_json::Value::String(s.value())),
            Lit::Int(i) => i
                .base10_parse::<i64>()
                .ok()
                .map(|v| serde_json::Value::Number(v.into())),
            Lit::Float(f) => f
                .base10_parse::<f64>()
                .ok()
                .and_then(serde_json::Number::from_f64)
                .map(serde_json::Value::Number),
            Lit::Bool(b) => Some(serde_json::Value::Bool(b.value)),
            _ => None,
        },
        // Method calls like "value".to_string()
        Expr::MethodCall(method_call) => {
            if method_call.method == "to_string" {
                // Get the receiver (the string literal)
                // Try direct match first
                if let Expr::Lit(ExprLit {
                    lit: Lit::Str(s), ..
                }) = method_call.receiver.as_ref()
                {
                    return Some(serde_json::Value::String(s.value()));
                }
                // Try to extract from nested expressions (e.g., if the receiver is wrapped)
                if let Some(value) = extract_value_from_expr(method_call.receiver.as_ref()) {
                    return Some(value);
                }
            }
            None
        }
        // Macro calls like vec![]
        Expr::Macro(ExprMacro { mac, .. }) => {
            if mac.path.is_ident("vec") {
                // Try to parse vec![] as empty array
                return Some(serde_json::Value::Array(vec![]));
            }
            None
        }
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use rstest::rstest;
    use serde_json::{Value, json};
    use vespera_core::schema::{Reference, Schema, SchemaRef};

    use super::*;

    fn parse_expr(src: &str) -> syn::Expr {
        syn::parse_str(src).expect("expr parses")
    }

    fn parse_fn(src: &str) -> syn::ItemFn {
        syn::parse_str(src).expect("fn parses")
    }

    fn parse_type(src: &str) -> syn::Type {
        syn::parse_str(src).expect("type parses")
    }

    // ---------- extract_value_from_expr ----------

    #[rstest]
    #[case::int("42", Some(Value::Number(42.into())))]
    #[case::string(r#""hello""#, Some(Value::String("hello".to_string())))]
    #[case::bool_true("true", Some(Value::Bool(true)))]
    #[case::bool_false("false", Some(Value::Bool(false)))]
    #[case::to_string(r#""hello".to_string()"#, Some(Value::String("hello".to_string())))]
    #[case::vec_macro("vec![]", Some(Value::Array(vec![])))]
    #[case::int_to_string("42.to_string()", Some(Value::Number(42.into())))]
    #[case::binary_unsupported("1 + 2", None)]
    #[case::method_call_non_to_string(r#""hello".len()"#, None)]
    #[case::byte_lit_unsupported("b'a'", None)]
    #[case::non_vec_macro(r#"println!("test")"#, None)]
    #[case::nested_paren_receiver(r#"("hello").to_string()"#, None)]
    #[case::non_literal_receiver("some_var.to_string()", None)]
    #[case::int_overflow("999999999999999999999999999999", None)]
    fn extract_value_from_expr_cases(#[case] src: &str, #[case] expected: Option<Value>) {
        assert_eq!(extract_value_from_expr(&parse_expr(src)), expected);
    }

    #[test]
    fn extract_value_from_expr_float_in_range() {
        // Float equality probe is separate — 12.34 round-trips but the assertion
        // needs a tolerance check rather than direct equality.
        let value = extract_value_from_expr(&parse_expr("12.34"));
        match value {
            Some(Value::Number(n)) => assert!((n.as_f64().unwrap() - 12.34).abs() < 0.001),
            other => panic!("expected number, got {other:?}"),
        }
    }

    #[test]
    fn extract_value_from_expr_float_parse_failure_does_not_panic() {
        // 1e999999 may parse to infinity or fail — either way the call must not panic.
        let _ = extract_value_from_expr(&parse_expr("1e999999"));
    }

    // ---------- get_type_default (re-exported helper) ----------

    #[rstest]
    #[case::string("String", Some(Value::String(String::new())))]
    #[case::i8("i8", Some(Value::Number(0.into())))]
    #[case::i16("i16", Some(Value::Number(0.into())))]
    #[case::i32("i32", Some(Value::Number(0.into())))]
    #[case::i64("i64", Some(Value::Number(0.into())))]
    #[case::u8("u8", Some(Value::Number(0.into())))]
    #[case::u16("u16", Some(Value::Number(0.into())))]
    #[case::u32("u32", Some(Value::Number(0.into())))]
    #[case::u64("u64", Some(Value::Number(0.into())))]
    #[case::bool("bool", Some(Value::Bool(false)))]
    #[case::unknown_custom("CustomType", None)]
    #[case::non_path_ref("&str", None)]
    #[case::tuple("(i32, String)", None)]
    #[case::array("[i32; 3]", None)]
    fn get_type_default_cases(#[case] src: &str, #[case] expected: Option<Value>) {
        assert_eq!(utils_get_type_default(&parse_type(src)), expected);
    }

    #[rstest]
    #[case::f32("f32")]
    #[case::f64("f64")]
    fn get_type_default_floats_present(#[case] src: &str) {
        assert!(utils_get_type_default(&parse_type(src)).is_some());
    }

    #[test]
    fn get_type_default_global_path_still_resolved() {
        // `::String` has a leading colon-colon but the last segment is still `String`.
        assert!(utils_get_type_default(&parse_type("::String")).is_some());
    }

    // ---------- find_function_in_file ----------

    #[rstest]
    #[case("foo", true)]
    #[case("bar", true)]
    #[case("baz", true)]
    #[case("nonexistent", false)]
    fn find_function_in_file_cases(#[case] needle: &str, #[case] expected: bool) {
        let file: syn::File = syn::parse_str(
            r"
            fn foo() {}
            fn bar() -> i32 { 42 }
            fn baz(x: i32) -> i32 { x }
            ",
        )
        .unwrap();
        assert_eq!(find_function_in_file(&file, needle).is_some(), expected);
    }

    // ---------- extract_default_value_from_function ----------

    #[test]
    fn extract_default_value_from_function_direct_expr() {
        let func = parse_fn("fn default_value() -> i32 { 42 }");
        assert_eq!(
            extract_default_value_from_function(&func),
            Some(Value::Number(42.into()))
        );
    }

    #[test]
    fn extract_default_value_from_function_explicit_return() {
        let func = parse_fn(r#"fn default_value() -> String { return "hello".to_string() }"#);
        assert_eq!(
            extract_default_value_from_function(&func),
            Some(Value::String("hello".to_string()))
        );
    }

    #[test]
    fn extract_default_value_from_function_no_value() {
        let func = parse_fn("fn default_value() { let x = 1; }");
        assert!(extract_default_value_from_function(&func).is_none());
    }

    // ---------- extract_schema_default_attr ----------

    #[rstest]
    #[case::with_value(
        syn::parse_quote!(#[schema(default = "42")]),
        Some("42".to_string()),
    )]
    #[case::no_default(syn::parse_quote!(#[schema(rename = "foo")]), None)]
    #[case::non_schema(syn::parse_quote!(#[serde(default)]), None)]
    fn extract_schema_default_attr_cases(
        #[case] attr: syn::Attribute,
        #[case] expected: Option<String>,
    ) {
        assert_eq!(extract_schema_default_attr(&[attr]), expected);
    }

    // ---------- parse_default_string_to_json_value ----------

    #[rstest]
    #[case::integer("42", json!(42))]
    #[case::float("2.72", json!(2.72))]
    #[case::bool("true", json!(true))]
    #[case::string_fallback("hello world", json!("hello world"))]
    fn parse_default_string_to_json_value_cases(#[case] input: &str, #[case] expected: Value) {
        assert_eq!(parse_default_string_to_json_value(input), expected);
    }

    // ---------- set_property_default ----------

    fn inline_prop(default: Option<Value>) -> SchemaRef {
        let mut schema = Schema::object();
        schema.default = default;
        SchemaRef::Inline(Box::new(schema))
    }

    fn assert_inline_default(
        properties: &BTreeMap<String, SchemaRef>,
        key: &str,
        expected: &Value,
    ) {
        let SchemaRef::Inline(prop) = properties.get(key).expect("property present") else {
            panic!("expected inline schema for {key}");
        };
        assert_eq!(prop.default.as_ref(), Some(expected));
    }

    #[test]
    fn set_property_default_sets_value_on_inline_schema_with_no_default() {
        let mut properties = BTreeMap::new();
        properties.insert("name".to_string(), inline_prop(None));

        set_property_default(&mut properties, "name", json!("Alice"));

        assert_inline_default(&properties, "name", &json!("Alice"));
    }

    #[test]
    fn set_property_default_does_not_overwrite_existing() {
        let mut properties = BTreeMap::new();
        properties.insert("name".to_string(), inline_prop(Some(json!("existing"))));

        set_property_default(&mut properties, "name", json!("new"));

        assert_inline_default(&properties, "name", &json!("existing"));
    }

    #[test]
    fn set_property_default_skips_ref_schema() {
        let mut properties = BTreeMap::new();
        properties.insert(
            "user".to_string(),
            SchemaRef::Ref(Reference::schema("User")),
        );

        set_property_default(&mut properties, "user", json!("ignored"));

        assert!(matches!(properties.get("user"), Some(SchemaRef::Ref(_))));
    }

    #[test]
    fn set_property_default_skips_missing_property() {
        let mut properties = BTreeMap::new();

        set_property_default(&mut properties, "nonexistent", json!(42));

        assert!(properties.is_empty());
    }

    // ---------- process_default_functions ----------

    #[test]
    fn process_default_functions_early_returns_when_properties_none() {
        let struct_item: syn::ItemStruct = syn::parse_str("struct Empty;").unwrap();
        let file_ast: syn::File = syn::parse_str("fn foo() {}").unwrap();
        let mut schema = Schema::object();
        schema.properties = None;

        process_default_functions(&struct_item, Some(&file_ast), &mut schema, &BTreeMap::new());

        assert!(schema.properties.is_none());
    }

    #[test]
    fn process_default_functions_applies_schema_default_attr() {
        let file_ast: syn::File = syn::parse_str("").unwrap();
        let struct_item: syn::ItemStruct =
            syn::parse_str(r#"pub struct Test { #[schema(default = "100")] pub count: i32 }"#)
                .unwrap();
        let mut schema = Schema::object();
        let props = schema.properties.get_or_insert_with(BTreeMap::new);
        props.insert(
            "count".to_string(),
            SchemaRef::Inline(Box::new(Schema::integer())),
        );

        process_default_functions(&struct_item, Some(&file_ast), &mut schema, &BTreeMap::new());

        assert_inline_default(schema.properties.as_ref().unwrap(), "count", &json!(100));
    }
}
